### ISSUE TITLE
Investigate the import of job_title

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/rbhl#69]
```
sqlite> select distinct(job_title) from legacy_suspectoccupationalcategory;
Yes-employed in suspect occupation
Yes-other occupation
No
Yes

```
This doesn't feel lots like things a person would type into a box labelled **Job Title** :)

**Comment by davidmiller** [comment]
On further eyeballing my guess would be that the data currently going into Suspect occupational category is what should be in Job title and vice versa.

**Comment by ghickman** [comment]
There's definitely a mixup here.

There are three fields of interest which I think relate to these UI fields.

* `Currently Employed?`
* `Suspect occupational Category`
* `Job Title`

The data has these values for two columns (listed above the table), the third is a list of what looks like job types/specific jobs.

```
Employed

     % | Count | Values
-------|-------|---------------
 0.25% |    11 | Unknown
 1.64% |    71 | Not applicable
 6.86% |   297 | No
89.25% |  3862 | Yes
```

```
Current_employment

     % | Count | Values
-------|-------|-----------------------------------
 0.07% |     3 | Yes-other occupation
 1.06% |    46 | Yes-employed in suspect occupation
11.39% |   493 | No
80.91% |  3501 | Yes
```
